CREATE SEQUENCE IF NOT EXISTS PUBLIC.users_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1
    START WITH 1
    NO CYCLE
;

CREATE TABLE IF NOT EXISTS users(
  id int8 NOT NULL DEFAULT NEXT VALUE FOR PUBLIC.users_seq,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  middle_name VARCHAR(50) NULL,
  phone_number VARCHAR(12),
  email TEXT NULL ,
  CONSTRAINT pk_users PRIMARY KEY (id)
);