CREATE SEQUENCE IF NOT EXISTS PUBLIC.orders_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1
    START WITH 1
    NO CYCLE
;

CREATE TABLE IF NOT EXISTS orders(
    id int8 NOT NULL DEFAULT NEXT VALUE FOR PUBLIC.orders_seq,
    description TEXT,
    amount INT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);